/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;


import BeansClasses.DepartmentBean;
import BeansClasses.FacultyBean;
import Database.DatabaseManager;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Umaid Mugheri
 */
public class DepartmentFrame extends javax.swing.JFrame {

    /**
     * Creates new form DepartmentFrame
     */
    public DepartmentFrame() throws Exception {
        initComponents();
        getFaculty();
       getDepartment();
    }
public void getDepartment() throws Exception 
    {
        FacultyBean bean=(FacultyBean)facultyComboBox.getSelectedItem();
            try{
            Vector v=DatabaseManager.getDepartment(bean.getId());
            System.out.println(v);
            deptList.setListData(v);
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,"Error: "+e.getMessage());
            }
    }
public void getFaculty() throws Exception
{
    try{
    Vector v=DatabaseManager.getFaculty();
    facultyComboBox.removeAllItems();
    for(int i=0;i<v.size();i++)
    {
    //System.out.println(v);
        facultyComboBox.addItem(v.elementAt(i));
    }
    }catch(Exception e){
        JOptionPane.showMessageDialog(this,"Error: "+e.getMessage());
    }
}

public void addDepartment() throws Exception
 {
             FacultyBean bean=(FacultyBean)facultyComboBox.getSelectedItem();
             if(bean==null)return;
             
                String deptName=departmentnameTextField.getText();
                String remarks=remarksTextArea.getText();
     try{
            int rows=DatabaseManager.addDepartment(bean.getId(),deptName,remarks);
            if(rows>0){
        JOptionPane.showMessageDialog(this,"Successfully Added");
        getDepartment();
        clear();
            }
    
    }catch(Exception e)
    {
        JOptionPane.showMessageDialog(this,"Error: "+e.getMessage());
    }
}
    


public void deleteDepartment() throws Exception{
   DepartmentBean bean= (DepartmentBean) deptList.getSelectedValue();
            if(bean==null) return;
    try{
        
    int rows =  DatabaseManager.deleteDepartment(bean.getDepartmentId());
    if(rows>0){
        JOptionPane.showMessageDialog(this,"Successfully Deleted");
         getFaculty();
         clear();
    }
    }catch(Exception e)
    {
        JOptionPane.showMessageDialog(this,"Error: "+e.getMessage());
    }
    
}

public void updateDepatment(){
    DepartmentBean bean=(DepartmentBean)deptList.getSelectedValue();
                     if(bean==null) return;
                String deptName=departmentnameTextField.getText();
                String remarks=remarksTextArea.getText();
    //System.out.println(name+":"+remarks);
    try{
        
    int rows =  DatabaseManager.updateDepartment(bean.getDepartmentId(),deptName,remarks);
    if(rows>0){
        JOptionPane.showMessageDialog(this,"Successfully Updated");
        getFaculty();
        clear();
    }
    }catch(Exception e)
    {
        JOptionPane.showMessageDialog(this,"Error: "+e.getMessage());
    }    
    
}

public void clear(){
    departmentidTextField.setText("");
    departmentnameTextField.setText("");
    remarksTextArea.setText("");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        departmentList = new javax.swing.JList();
        DepartmenLabel = new javax.swing.JLabel();
        facultyLabel = new javax.swing.JLabel();
        depatmentidLabel = new javax.swing.JLabel();
        darptmentnameLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        facultyComboBox = new javax.swing.JComboBox();
        remarksLabel = new javax.swing.JLabel();
        departmentidTextField = new javax.swing.JTextField();
        departmentnameTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        remarksTextArea = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        deptList = new javax.swing.JList();

        departmentList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(departmentList);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(798, 456));
        setMinimumSize(new java.awt.Dimension(798, 456));
        setPreferredSize(new java.awt.Dimension(798, 456));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DepartmenLabel.setFont(new java.awt.Font("Times New Roman", 0, 40)); // NOI18N
        DepartmenLabel.setText("Department");
        getContentPane().add(DepartmenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 24, 242, -1));

        facultyLabel.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        facultyLabel.setText("Faculty");
        getContentPane().add(facultyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 93, 57, -1));

        depatmentidLabel.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        depatmentidLabel.setText("DEPARTMENT ID");
        getContentPane().add(depatmentidLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 119, -1, -1));

        darptmentnameLabel.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        darptmentnameLabel.setText("DEPARTMENT NAME");
        getContentPane().add(darptmentnameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, 20));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 540, -1, -1));

        facultyComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(facultyComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 89, 168, -1));

        remarksLabel.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        remarksLabel.setText("REMARKS");
        getContentPane().add(remarksLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        departmentidTextField.setEditable(false);
        departmentidTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentidTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(departmentidTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 115, 59, -1));

        departmentnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentnameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(departmentnameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 253, -1));

        remarksTextArea.setColumns(20);
        remarksTextArea.setRows(5);
        jScrollPane1.setViewportView(remarksTextArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 253, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel6.setText("DEPARTMENTS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 89, -1, -1));

        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, 33));

        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, 33));

        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 320, 200, 32));

        clearButton.setText("CLEAR");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, -1, 33));

        backButton.setText("BACK");
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, -1, 33));

        deptList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                deptListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(deptList);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 116, 176, 171));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void departmentidTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentidTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departmentidTextFieldActionPerformed

    private void departmentnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departmentnameTextFieldActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
       updateDepatment();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        clear();        // TODO add your handling code here:
    }//GEN-LAST:event_clearButtonActionPerformed

    private void facultyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyComboBoxActionPerformed
        try {
            getDepartment();
        } catch (Exception ex) {
            Logger.getLogger(DepartmentFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_facultyComboBoxActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        try{
             addDepartment();
             
        } catch (Exception ex){
             Logger.getLogger(DepartmentFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        try {
            deleteDepartment();        // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(DepartmentFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void deptListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_deptListValueChanged
        
        DepartmentBean bean=(DepartmentBean) deptList.getSelectedValue();
            
            departmentidTextField.setText(""+bean.getDepartmentId());
            departmentnameTextField.setText(bean.getDepartmentName());
            remarksTextArea.setText(bean.getRemarks());
    }//GEN-LAST:event_deptListValueChanged
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DepartmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DepartmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DepartmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DepartmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DepartmentFrame().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(DepartmentFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DepartmenLabel;
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel darptmentnameLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JList departmentList;
    private javax.swing.JTextField departmentidTextField;
    private javax.swing.JTextField departmentnameTextField;
    private javax.swing.JLabel depatmentidLabel;
    private javax.swing.JList deptList;
    private javax.swing.JComboBox facultyComboBox;
    private javax.swing.JLabel facultyLabel;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel remarksLabel;
    private javax.swing.JTextArea remarksTextArea;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables

    //To change body of generated methods, choose Tools | Templates.

    

   
   
    }

