/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import BeansClasses.FacultyBean;
import Database.DatabaseManager;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Umaid Mugheri
 */
public class FacultyFrame extends javax.swing.JFrame {

    /**
     * Creates new form FacultyFrame
     */
    public FacultyFrame() throws Exception {
        initComponents();
        getFaculty();
    }
    
public void getFaculty() throws Exception
{
    try{
    Vector v=DatabaseManager.getFaculty();
    //System.out.println(v);
    facultyList.setListData(v);
    }catch(Exception e){
        JOptionPane.showMessageDialog(this,"Error: "+e.getMessage());
    }
}

public void addFaculty(){
    
    String name=nameTextField.getText();
    String remarks=remarksTextArea.getText();
    //System.out.println(name+":"+remarks);
    try{
        
    int rows =  DatabaseManager.addFaculty(name,remarks);
    if(rows>0){
        JOptionPane.showMessageDialog(this,"Successfully Added");
        getFaculty();
        clear();
    }
    }catch(Exception e)
    {
        JOptionPane.showMessageDialog(this,"Error: "+e.getMessage());
    }
}

public void deleteFaculty() throws Exception{
   FacultyBean bean=(FacultyBean)facultyList.getSelectedValue();
            
    try{
        
    int rows =  DatabaseManager.deleteFaculty(bean.getId());
    if(rows>0){
        JOptionPane.showMessageDialog(this,"Successfully Deleted");
         getFaculty();
         clear();
    }
    }catch(Exception e)
    {
        JOptionPane.showMessageDialog(this,"Error: "+e.getMessage());
    }
    
}

public void updateFaculty(){
    FacultyBean bean=(FacultyBean)facultyList.getSelectedValue();

    String name=nameTextField.getText();
    String remarks=remarksTextArea.getText();
    //System.out.println(name+":"+remarks);
    try{
        
    int rows =  DatabaseManager.updateFaculty(bean.getId(),name,remarks);
    if(rows>0){
        JOptionPane.showMessageDialog(this,"Successfully Updated");
        getFaculty();
        clear();
    }
    }catch(Exception e)
    {
        JOptionPane.showMessageDialog(this,"Error: "+e.getMessage());
    }    
    
}

public void clear(){
    idTextField.setText("");
    nameTextField.setText("");
    remarksTextArea.setText("");
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        facultyLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        remarksLabel = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        remarksTextArea = new javax.swing.JTextArea();
        idLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        facultyList = new javax.swing.JList();
        deleteButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(735, 433));
        setMinimumSize(new java.awt.Dimension(735, 433));
        setPreferredSize(new java.awt.Dimension(735, 433));
        getContentPane().setLayout(null);

        facultyLabel.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        facultyLabel.setText("FACULTY ");
        getContentPane().add(facultyLabel);
        facultyLabel.setBounds(290, 20, 140, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setText("FACULTIES");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(520, 80, 90, 19);

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        nameLabel.setText("NAME");
        getContentPane().add(nameLabel);
        nameLabel.setBounds(90, 180, 60, 19);

        remarksLabel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        remarksLabel.setText("REMARKS");
        getContentPane().add(remarksLabel);
        remarksLabel.setBounds(90, 250, 80, 19);

        idTextField.setEditable(false);
        idTextField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(idTextField);
        idTextField.setBounds(190, 120, 80, 30);

        nameTextField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(nameTextField);
        nameTextField.setBounds(190, 180, 160, 30);

        remarksTextArea.setColumns(20);
        remarksTextArea.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        remarksTextArea.setRows(5);
        jScrollPane1.setViewportView(remarksTextArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(190, 240, 260, 76);

        idLabel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        idLabel.setText("ID");
        getContentPane().add(idLabel);
        idLabel.setBounds(90, 120, 40, 19);

        facultyList.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        facultyList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                facultyListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(facultyList);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(520, 110, 140, 210);

        deleteButton.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteButton);
        deleteButton.setBounds(520, 330, 140, 40);

        addButton.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addButton);
        addButton.setBounds(90, 330, 80, 40);

        updateButton.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateButton);
        updateButton.setBounds(200, 330, 80, 40);

        clearButton.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        clearButton.setText("CLEAR");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clearButton);
        clearButton.setBounds(310, 330, 80, 40);

        backButton.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        backButton.setText("BACK");
        getContentPane().add(backButton);
        backButton.setBounds(420, 330, 80, 40);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        clear();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
       addFaculty();
    }//GEN-LAST:event_addButtonActionPerformed

    private void facultyListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_facultyListValueChanged
            FacultyBean bean=(FacultyBean)facultyList.getSelectedValue();
            
            idTextField.setText(""+bean.getId());
            nameTextField.setText(bean.getName());
            remarksTextArea.setText(bean.getRemarks());
            
            
    }//GEN-LAST:event_facultyListValueChanged

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        try {
            deleteFaculty();        // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(FacultyFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
            updateFaculty();        // TODO add your handling code here:
    }//GEN-LAST:event_updateButtonActionPerformed

    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacultyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacultyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacultyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacultyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FacultyFrame().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FacultyFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(FacultyFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel facultyLabel;
    private javax.swing.JList facultyList;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel remarksLabel;
    private javax.swing.JTextArea remarksTextArea;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
