/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;
import BeansClasses.ProgramBean;
import BeansClasses.DepartmentBean;
import BeansClasses.FacultyBean;
import Database.DatabaseManager;
import static Database.DatabaseManager.updateProgram;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Umaid Mugheri
 */
public class ProgramFrame extends javax.swing.JFrame {
    private Object deapartmentComboBox;
    private Object programnameTextField;

    /**
     * Creates new form ProgramFrame
     */
    public ProgramFrame() throws Exception {
        initComponents();
         getFaculty();
        getDepartment();
       getProgram();
        
        
    }  
         public void getProgram() throws Exception 
    {
        DepartmentBean bean=(DepartmentBean)departmentComboBox.getSelectedItem();
        
        
            try{
            Vector v=DatabaseManager.getProgram(bean.getDepartmentId());
            System.out.println(v);
            programList.setListData(v);
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,"Error: "+e.getMessage());
            }
    }
    
    public void getDepartment() 
    {
        FacultyBean bean=(FacultyBean)facultyComboBox.getSelectedItem();
        
        
            try{
            Vector v=DatabaseManager.getDepartment(bean.getId());
    departmentComboBox.removeAllItems();
    for(int i=0;i<v.size();i++)
    {
    //System.out.println(v);
        departmentComboBox.addItem(v.elementAt(i));
    }
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,"Error: "+e.getMessage());
            }
    }
public void getFaculty() throws Exception
{
    try{
    Vector v=DatabaseManager.getFaculty();
    facultyComboBox.removeAllItems();
    for(int i=0;i<v.size();i++)
    {
    //System.out.println(v);
        facultyComboBox.addItem(v.elementAt(i));
    }
    }catch(Exception e){
        JOptionPane.showMessageDialog(this,"Error: "+e.getMessage());
    }
}

public void addProgram() throws Exception
 {
             DepartmentBean bean=(DepartmentBean)departmentComboBox.getSelectedItem();
             if(bean==null)return;
             
                String ProgName=progamnameTextField.getText();
                int duarationInSem= Integer.parseInt(durationTextField.getText());
                String remarks=remarksTextArea.getText();
     try{
            int rows=DatabaseManager.addProgram(bean.getDepartmentId(),ProgName,duarationInSem,remarks);
            if(rows>0){
        JOptionPane.showMessageDialog(this,"Successfully Added");
        getDepartment();
        clear();
            }
    
    }catch(Exception e)
    {
        JOptionPane.showMessageDialog(this,"Error: "+e.getMessage());
    }
}
    


public void deleteProgram() throws Exception{
   ProgramBean bean= (ProgramBean) programList.getSelectedValue();
            if(bean==null) return;
    try{
        
    int rows =  DatabaseManager.deleteProgram(bean.getProgramId());
    if(rows>0){
        JOptionPane.showMessageDialog(this,"Successfully Deleted");
         getFaculty();
         clear();
    }
    }catch(Exception e)
    {
        JOptionPane.showMessageDialog(this,"Error: "+e.getMessage());
    }
    
}

public void updateProgram(){
    ProgramBean bean=(ProgramBean) programList.getSelectedValue();
                     if(bean==null) return;
                String ProgName=progamnameTextField.getText();
                int duarationInSem= Integer.parseInt(durationTextField.getText());
                String remarks=remarksTextArea.getText();
    //System.out.println(name+":"+remarks);
    try{
        
    int rows =  DatabaseManager.updateProgram(bean.getProgramId(),ProgName,duarationInSem,remarks);
    if(rows>0){
        JOptionPane.showMessageDialog(this,"Successfully Updated");
        getFaculty();
        clear();
    }
    }catch(Exception e)
    {
        JOptionPane.showMessageDialog(this,"Error: "+e.getMessage());
    }    
    
}

public void clear(){
    programidTextField.setText("");
    progamnameTextField.setText("");
    durationTextField.setText("");
    remarksTextArea.setText("");
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProgramLabel = new javax.swing.JLabel();
        facultyLabel = new javax.swing.JLabel();
        departmentLabel = new javax.swing.JLabel();
        programidLabel = new javax.swing.JLabel();
        progamnameLabel = new javax.swing.JLabel();
        durationLabel = new javax.swing.JLabel();
        remarksLabel = new javax.swing.JLabel();
        facultyComboBox = new javax.swing.JComboBox();
        departmentComboBox = new javax.swing.JComboBox();
        programidTextField = new javax.swing.JTextField();
        progamnameTextField = new javax.swing.JTextField();
        durationTextField = new javax.swing.JTextField();
        semesterLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        remarksTextArea = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        programList = new javax.swing.JList();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(781, 521));
        setMinimumSize(new java.awt.Dimension(781, 521));
        getContentPane().setLayout(null);

        ProgramLabel.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        ProgramLabel.setText("Program");
        getContentPane().add(ProgramLabel);
        ProgramLabel.setBounds(320, 20, 140, 36);

        facultyLabel.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        facultyLabel.setText("Faculty");
        getContentPane().add(facultyLabel);
        facultyLabel.setBounds(30, 80, 50, 18);

        departmentLabel.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        departmentLabel.setText("Department");
        getContentPane().add(departmentLabel);
        departmentLabel.setBounds(20, 130, 90, 18);

        programidLabel.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        programidLabel.setText("Program ID");
        getContentPane().add(programidLabel);
        programidLabel.setBounds(20, 180, 90, 18);

        progamnameLabel.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        progamnameLabel.setText("Program Name");
        getContentPane().add(progamnameLabel);
        progamnameLabel.setBounds(20, 230, 100, 18);

        durationLabel.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        durationLabel.setText("Duration");
        getContentPane().add(durationLabel);
        durationLabel.setBounds(20, 290, 90, 18);

        remarksLabel.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        remarksLabel.setText("Remarks");
        getContentPane().add(remarksLabel);
        remarksLabel.setBounds(20, 340, 60, 18);

        facultyComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(facultyComboBox);
        facultyComboBox.setBounds(156, 80, 350, 20);

        departmentComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(departmentComboBox);
        departmentComboBox.setBounds(156, 130, 350, 20);

        programidTextField.setEditable(false);
        getContentPane().add(programidTextField);
        programidTextField.setBounds(149, 180, 140, 20);

        progamnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                progamnameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(progamnameTextField);
        progamnameTextField.setBounds(149, 230, 360, 30);
        getContentPane().add(durationTextField);
        durationTextField.setBounds(149, 280, 80, 30);

        semesterLabel.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        semesterLabel.setText("In Semester");
        getContentPane().add(semesterLabel);
        semesterLabel.setBounds(270, 280, 90, 18);

        remarksTextArea.setColumns(20);
        remarksTextArea.setRows(5);
        jScrollPane1.setViewportView(remarksTextArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(140, 320, 390, 96);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel9.setText("PROGRAM");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(580, 80, 80, 18);

        programList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                programListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(programList);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(550, 130, 160, 290);

        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addButton);
        addButton.setBounds(110, 430, 70, 30);

        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateButton);
        updateButton.setBounds(193, 430, 80, 30);

        clearButton.setText("CLEAR");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clearButton);
        clearButton.setBounds(280, 430, 70, 30);

        jButton4.setText("BACK");
        getContentPane().add(jButton4);
        jButton4.setBounds(370, 430, 70, 30);

        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteButton);
        deleteButton.setBounds(570, 430, 69, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        try {
            addProgram();     // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(ProgramFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void progamnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_progamnameTextFieldActionPerformed

    }//GEN-LAST:event_progamnameTextFieldActionPerformed

    private void facultyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyComboBoxActionPerformed
        
            getDepartment();
      

    }//GEN-LAST:event_facultyComboBoxActionPerformed

    private void departmentComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentComboBoxActionPerformed
        try {
            // TODO add your handling code here:
            getProgram();
        } catch (Exception ex) {
            Logger.getLogger(ProgramFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_departmentComboBoxActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
            
        try {      
            deleteProgram();
// TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(ProgramFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
            updateProgram();
         // TODO add your handling code here:
    }//GEN-LAST:event_updateButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
          clear();  
        // TODO add your handling code here:
    }//GEN-LAST:event_clearButtonActionPerformed

    private void programListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_programListValueChanged
        // TODO add your handling code here:
           ProgramBean bean=(ProgramBean) programList.getSelectedValue();
            
            programidTextField.setText(""+bean.getProgramId());
           progamnameTextField.setText(bean.getProgramName());
           durationTextField.setText(""+bean.getDuration());
            remarksTextArea.setText(bean.getRemarks());
    }//GEN-LAST:event_programListValueChanged
         /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgramFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgramFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgramFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgramFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ProgramFrame().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(ProgramFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ProgramLabel;
    private javax.swing.JButton addButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JComboBox departmentComboBox;
    private javax.swing.JLabel departmentLabel;
    private javax.swing.JLabel durationLabel;
    private javax.swing.JTextField durationTextField;
    private javax.swing.JComboBox facultyComboBox;
    private javax.swing.JLabel facultyLabel;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel progamnameLabel;
    private javax.swing.JTextField progamnameTextField;
    private javax.swing.JList programList;
    private javax.swing.JLabel programidLabel;
    private javax.swing.JTextField programidTextField;
    private javax.swing.JLabel remarksLabel;
    private javax.swing.JTextArea remarksTextArea;
    private javax.swing.JLabel semesterLabel;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables



    
}
